// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Shipment struct {
	ID             pgtype.UUID        `json:"id"`
	OrderID        string             `json:"order_id"`
	TrackingNumber string             `json:"tracking_number"`
	DeliveryDate   pgtype.Timestamptz `json:"delivery_date"`
	Status         string             `json:"status"`
	Confirmed      bool               `json:"confirmed"`
	Name           string             `json:"name"`
	Street         string             `json:"street"`
	City           string             `json:"city"`
	Country        string             `json:"country"`
	WorkflowID     string             `json:"workflow_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
