// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchPendingOutboxEvents = `-- name: FetchPendingOutboxEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, status, retry_count, created_at, updated_at FROM outbox_events
WHERE  status IN ('PENDING', 'FAILED')
  AND  retry_count < $1
ORDER  BY created_at
LIMIT  $2
`

type FetchPendingOutboxEventsParams struct {
	RetryCount int32 `json:"retry_count"`
	Limit      int32 `json:"limit"`
}

func (q *Queries) FetchPendingOutboxEvents(ctx context.Context, arg FetchPendingOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, fetchPendingOutboxEvents, arg.RetryCount, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (
    id, aggregate_type, aggregate_id, event_type, payload, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, 'PENDING', NOW(), NOW()
)
`

type InsertOutboxEventParams struct {
	ID            pgtype.UUID `json:"id"`
	AggregateType string      `json:"aggregate_type"`
	AggregateID   string      `json:"aggregate_id"`
	EventType     string      `json:"event_type"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET    status      = 'FAILED',
       retry_count = retry_count + 1,
       updated_at  = NOW()
WHERE  id = $1
`

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, id)
	return err
}

const markOutboxEventSent = `-- name: MarkOutboxEventSent :exec
UPDATE outbox_events
SET    status = 'SENT', updated_at = NOW()
WHERE  id = $1
`

func (q *Queries) MarkOutboxEventSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventSent, id)
	return err
}
