// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error)
	FetchPendingOutboxEvents(ctx context.Context, arg FetchPendingOutboxEventsParams) ([]OutboxEvent, error)
	GetShipmentByID(ctx context.Context, id pgtype.UUID) (Shipment, error)
	GetShipmentByOrderID(ctx context.Context, orderID string) (Shipment, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	MarkOutboxEventFailed(ctx context.Context, id pgtype.UUID) error
	MarkOutboxEventSent(ctx context.Context, id pgtype.UUID) error
	UpdateShipment(ctx context.Context, arg UpdateShipmentParams) (Shipment, error)
}

var _ Querier = (*Queries)(nil)
