// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error)
	GetShipmentByID(ctx context.Context, id pgtype.UUID) (Shipment, error)
	GetShipmentByOrderID(ctx context.Context, orderID string) (Shipment, error)
	UpdateShipment(ctx context.Context, arg UpdateShipmentParams) (Shipment, error)
}

var _ Querier = (*Queries)(nil)
