// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipment.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipments (
    id,
    order_id,
    tracking_number,
    delivery_date,
    status,
    confirmed,
    name,
    street,
    city,
    country,
    created_at,
    updated_at,
	workflow_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (order_id) DO NOTHING
RETURNING id, order_id, tracking_number, delivery_date, status, confirmed, name, street, city, country, created_at, updated_at, workflow_id
`

type CreateShipmentParams struct {
	ID             pgtype.UUID        `json:"id"`
	OrderID        string             `json:"order_id"`
	TrackingNumber string             `json:"tracking_number"`
	DeliveryDate   pgtype.Timestamptz `json:"delivery_date"`
	Status         string             `json:"status"`
	Confirmed      bool               `json:"confirmed"`
	Name           string             `json:"name"`
	Street         string             `json:"street"`
	City           string             `json:"city"`
	Country        string             `json:"country"`
	WorkflowID     string             `json:"workflow_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.ID,
		arg.OrderID,
		arg.TrackingNumber,
		arg.DeliveryDate,
		arg.Status,
		arg.Confirmed,
		arg.Name,
		arg.Street,
		arg.City,
		arg.Country,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.WorkflowID,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TrackingNumber,
		&i.DeliveryDate,
		&i.Status,
		&i.Confirmed,
		&i.Name,
		&i.Street,
		&i.City,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkflowID,
	)
	return i, err
}

const getShipmentByID = `-- name: GetShipmentByID :one
SELECT id, order_id, tracking_number, delivery_date, status, confirmed, name, street, city, country, created_at, updated_at, workflow_id FROM shipments
WHERE id = $1
`

func (q *Queries) GetShipmentByID(ctx context.Context, id pgtype.UUID) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipmentByID, id)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TrackingNumber,
		&i.DeliveryDate,
		&i.Status,
		&i.Confirmed,
		&i.Name,
		&i.Street,
		&i.City,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkflowID,
	)
	return i, err
}

const getShipmentByOrderID = `-- name: GetShipmentByOrderID :one
SELECT id, order_id, tracking_number, delivery_date, status, confirmed, name, street, city, country, created_at, updated_at, workflow_id FROM shipments
WHERE order_id = $1
`

func (q *Queries) GetShipmentByOrderID(ctx context.Context, orderID string) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipmentByOrderID, orderID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TrackingNumber,
		&i.DeliveryDate,
		&i.Status,
		&i.Confirmed,
		&i.Name,
		&i.Street,
		&i.City,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkflowID,
	)
	return i, err
}

const updateShipment = `-- name: UpdateShipment :one
UPDATE shipments
SET
    tracking_number = $2,
    delivery_date   = $3,
    status          = $4,
    confirmed       = $5,
    name            = $6,
    street          = $7,
    city            = $8,
    country         = $9,
    updated_at      = $10
WHERE id = $1
RETURNING id, order_id, tracking_number, delivery_date, status, confirmed, name, street, city, country, created_at, updated_at, workflow_id
`

type UpdateShipmentParams struct {
	ID             pgtype.UUID        `json:"id"`
	TrackingNumber string             `json:"tracking_number"`
	DeliveryDate   pgtype.Timestamptz `json:"delivery_date"`
	Status         string             `json:"status"`
	Confirmed      bool               `json:"confirmed"`
	Name           string             `json:"name"`
	Street         string             `json:"street"`
	City           string             `json:"city"`
	Country        string             `json:"country"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateShipment(ctx context.Context, arg UpdateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, updateShipment,
		arg.ID,
		arg.TrackingNumber,
		arg.DeliveryDate,
		arg.Status,
		arg.Confirmed,
		arg.Name,
		arg.Street,
		arg.City,
		arg.Country,
		arg.UpdatedAt,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TrackingNumber,
		&i.DeliveryDate,
		&i.Status,
		&i.Confirmed,
		&i.Name,
		&i.Street,
		&i.City,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkflowID,
	)
	return i, err
}
